apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ten-nine 
  description: Secure Supply Chain Example for Quarkus Java example with advanced continuous integration pipeline covering building, CVE scanning, security scanning, signatures,  attestations, SLSA provenance and SBOM along with Gitops-based continuous deployment   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:
    # ArgoCD apps from this template used rhtap-gitops as the grouping
    argocd/app-selector: rhtap/gitops=ten-nine
    janus-idp.io/tekton: ten-nine
    backstage.io/kubernetes-id: ten-nine 
    backstage.io/techdocs-ref: dir:. 
    quay.io/repository-slug: chr1st1an-org/ten-nine  
  tags: ["java", "quarkus", "sscs", "sbom", "acs"] 
spec:
  type: service
  owner: user:guest 
  lifecycle: experimental
 